### ISSUE TITLE
cant get it working on replit

### ISSUE THREAD

**Issue by Jeremy5909** [vivaansinghvi07/dreamberd-interpreter#12]
ive been trying to use this with replit to make a template but when I pip install dreamberd and pip install requests, but when I try to dreamberd main.db, I get

`export LC_ALL=C`

**Comment by Jeremy5909** [comment]
fixed with
`export LC_ALL=C`
not sure what it means tho

**Comment by vivaansinghvi07** [comment]
I don’t know much about Replit either, where do you put this export?

**Comment by Jeremy5909** [comment]
type it in shell is what i did

**Comment by Jeremy5909** [comment]
ima give up there too many errors idk if anyone else can get it workign

**Comment by vivaansinghvi07** [comment]
Does it seem to be an issue with Replit or the package?

**Comment by vivaansinghvi07** [comment]
Ah okay, I did some research and it seems like LC_ALL controls language and locale, it must not be set on the Replit cloud machines. I’ll patch the interpreter to default to the dollar sign if no locale is found. Thanks for letting me know!

**Comment by Jeremy5909** [comment]
alr cool

**Comment by vivaansinghvi07** [comment]
What class was the error (like LocaleError, InterpretationError) that you got?

**Comment by Jeremy5909** [comment]
locale.Error

**Comment by vivaansinghvi07** [comment]
Okay, expect a fix within the next five minutes!

**Comment by Jeremy5909** [comment]
kewl

**Comment by gracetastic** [comment]
I am now invested in this endeavor. I hope to see a solution in 3 minutes.

**Comment by vivaansinghvi07** [comment]
locale issues should be fixed

**Comment by Jeremy5909** [comment]
idk how to make it a template but now you can fulfill ur dreamberd means online 
https://replit.com/@jherczeg27/Dreamberd?v=1#main.db
