### ISSUE TITLE
maybe have const const const have specific label so its easier to sort when looking through issues or smtn

### ISSUE THREAD

**Issue by Jeremy5909** [vivaansinghvi07/dreamberd-interpreter#13]
maybe so

**Comment by vivaansinghvi07** [comment]
All issues for const const const variables go to the dreamberd-interpreter-globals repo, and i’ve just cleared the old “Create Global Variable” issues from this repo

**Comment by Jeremy5909** [comment]
i meant like have the issues automatically made have a tag

**Comment by vivaansinghvi07** [comment]
ohh gotcha. I was thinking that issues on that other repo should only be for creating variables, any functionality issues should go here even if it’s related to the const const const variables
