### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by trainb0y** [vivaansinghvi07/dreamberd-interpreter#16]
Not exactly sure how to write this, hopefully this doesn't come off as too demanding/entitled.

There doesn't seem to be a license for this, and I'm wondering if there are any plans for it to be put under a permissive license? 
Totally fine and understandable if not though.

I mostly ask because I want to try my hand at a direct Kotlin port, and write some Horrible Duct Tape™ to make a Minecraft mod at least partly in DreamBerd, and I'm too lazy to want to start from scratch.

**Comment by vivaansinghvi07** [comment]
Apologies, I thought I released this with a license. I will add one now, it will be the MIT license.
